{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#include <Python.h>\n",
    "#include <wiringPi.h>\n",
    "#define DEVICE_FILENAME  \"/dev/Ex_06\"    \n",
    "#include \"simple.h\"\n",
    "\n",
    "static PyObject *blink(PyObject *self, PyObject *args)\n",
    "{\n",
    "    int ledPin = 0, pinNum = 0;\n",
    "    int i = 0; // for\n",
    "\tledHW ledhw;\n",
    "    \n",
    "    if(!PyArg_ParseTuple(args, \"i\", &pinNum))\n",
    "        return NULL;\n",
    "\t\n",
    "    \n",
    "    wiringPiSetupGpio();\n",
    "    pinMode(ledPin, OUTPUT);\n",
    "    \n",
    "    for(i=0; i<5; i++){\n",
    "        digitalWrite(ledPin, HIGH);\n",
    "        delay(500);\n",
    "        digitalWrite(ledPin, LOW);\n",
    "        delay(500);\n",
    "    }\n",
    "    Py_RETURN_NONE;\n",
    "}\n",
    "\n",
    "static PyObject *led(PyObject *self, PyObject *args) {\n",
    "\tint pin = 0;\n",
    "\tint order = 0;\n",
    "\tint fd = 0;\n",
    "\tint *inputPin;\n",
    "\tchar *inputOrder;\n",
    "\n",
    "\tif (!PyArg_ParseTuble(args, \"i s\", &inputPin,&inputOrder))\n",
    "\t\treturn NULL;\n",
    "\tmemset(&ledhw, 0, sizeof(ledhw));\n",
    "\tint size = sizeof(ledhw);\n",
    "\tledPin = pinNum;\n",
    "\tpin = inputPin;\n",
    "\tif (strcmp(inputOrder, \"1\"))\n",
    "\t\torder = 1;\n",
    "\telse\n",
    "\t\torder = 0;\n",
    "\tprintf(\"%d, %d 입니다.\", pin, order);\n",
    "\tledhw.pin = pin;\n",
    "\tledhw.funcNum = order;\n",
    "\tfd = open(DEVICE_FILENAME, O_RDWR | O_NDELAY);\n",
    "\tif (fd >= 0) {\n",
    "\t\tprintf(\"send ledctl to device dirver\\n\");\n",
    "\t\tioctl(fd, MY_IOC_SET, &ledhw);\n",
    "\t\tioctl(fd, MY_IOC_GPIO_SETFUNC);\n",
    "\t}\n",
    "\telse\n",
    "\t\tprintf(\"코드다시짜임마\");\n",
    "\tclose(fd);\n",
    "\n",
    "\treturn NULL;\n",
    "\t\n",
    "\n",
    "}\n",
    "static PyMethodDef keywdarg_methods[] = {\n",
    "    {\"blink\", (PyCFunction)blink, METH_VARARGS, NULL},\n",
    "    {NULL, NULL, 0, NULL}   /* sentinel */\n",
    "};\n",
    "\n",
    "static struct PyModuleDef keywdargmodule = {\n",
    "    PyModuleDef_HEAD_INIT,\n",
    "    \"blink\",\n",
    "    NULL,\n",
    "    -1,\n",
    "    keywdarg_methods\n",
    "};\n",
    "\n",
    "PyMODINIT_FUNC PyInit_ex3(void)\n",
    "{\n",
    "    return PyModule_Create(&keywdargmodule);\n",
    "}\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
